
import java.awt.Image;
import java.io.File;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JLabel;


/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Legion
 */
public class secondframe extends javax.swing.JFrame {

    
      public void scaleimage__logo(String path , JLabel a){
        ImageIcon icon = new ImageIcon (path);
        Image img = icon.getImage();
        Image imgscale = img.getScaledInstance(a.getWidth(),a.getHeight(),Image.SCALE_SMOOTH);
        ImageIcon scaledIcon = new ImageIcon(imgscale);
        a.setIcon(scaledIcon);
    }
    /**
     * Creates new form  
     */
    public secondframe() {
        initComponents();
         scaleimage__logo("src\\upload.png" , up2);
        scaleimage__logo("src\\photo\\2nd.png", logo);
        scaleimage__logo("src\\photo\\firstback.jpg", back);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        logo = new javax.swing.JLabel();
        up2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        back = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("First");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(239, 122, 52)));
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 310, 560, 50));
        getContentPane().add(logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 60, 230, 150));

        up2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                up2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                up2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                up2MouseExited(evt);
            }
        });
        getContentPane().add(up2, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 310, 60, 50));

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton1.setText("Save");
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 370, 180, 40));

        back.setBackground(new java.awt.Color(255, 255, 255));
        back.setOpaque(true);
        getContentPane().add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 720, 720));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void up2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_up2MouseClicked
        // TODO add your handling code here:
        try {
            JFileChooser x = new JFileChooser();
            int responce = x.showOpenDialog(null);

            if (responce == JFileChooser.APPROVE_OPTION){
                File file = new File(x.getSelectedFile().getAbsolutePath());
                //Desktop.getDesktop().open(file);
                //System.out.println(file);
                jLabel3.setText(file.toString());
            }
        }
        catch (Exception e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_up2MouseClicked

    private void up2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_up2MouseEntered
        // TODO add your handling code here:
        scaleimage__logo("src\\photo\\imgup.png" , up2);
    }//GEN-LAST:event_up2MouseEntered

    private void up2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_up2MouseExited
        // TODO add your handling code here:
        scaleimage__logo("src\\upload.png" , up2);
    }//GEN-LAST:event_up2MouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Firstframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Firstframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Firstframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Firstframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new secondframe().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel back;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel logo;
    private javax.swing.JLabel up2;
    // End of variables declaration//GEN-END:variables
}
